// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InteriumMiddleware.Migrations.Accounts
{
    [DbContext(typeof(AccountsContext))]
    [Migration("20201110145219_accountsMit")]
    partial class accountsMit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InteriumMiddleware.Models.Account", b =>
                {
                    b.Property<string>("account_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("account_numbernumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("account_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("display_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("provider_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("update_timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("account_id");

                    b.HasIndex("account_numbernumber");

                    b.HasIndex("provider_id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("InteriumMiddleware.Models.Account_Number", b =>
                {
                    b.Property<string>("number")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("sort_code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("swift_bic")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("number");

                    b.ToTable("Account_Number");
                });

            modelBuilder.Entity("InteriumMiddleware.Models.Provider", b =>
                {
                    b.Property<string>("provider_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("display_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logo_uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("provider_id");

                    b.ToTable("Provider");
                });

            modelBuilder.Entity("InteriumMiddleware.Models.Account", b =>
                {
                    b.HasOne("InteriumMiddleware.Models.Account_Number", "account_number")
                        .WithMany()
                        .HasForeignKey("account_numbernumber");

                    b.HasOne("InteriumMiddleware.Models.Provider", "provider")
                        .WithMany()
                        .HasForeignKey("provider_id");
                });
#pragma warning restore 612, 618
        }
    }
}
